# Generated by Django 3.1.1 on 2020-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightApp', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='flights',
            field=models.ManyToManyField(related_name='passengers', to='FlightApp.Flight'),
        ),
    ]
