# Generated by Django 3.1.1 on 2020-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201101_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='min_bid',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings_commented', to='auctions.Comment'),
        ),
    ]
