# Generated by Django 3.1.1 on 2020-11-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201101_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='listings_commented', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
