# Generated by Django 3.1.1 on 2020-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201101_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(null=True, related_name='listings_commented', to='auctions.Comment'),
        ),
    ]
