# Generated by Django 3.1.1 on 2020-11-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20201101_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creation_date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings_commented', to='auctions.Comment'),
        ),
    ]
