# Generated by Django 3.1.1 on 2020-11-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201101_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings_commented', to='auctions.Comment'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='creation_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
