# Generated by Django 3.1.1 on 2020-11-03 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20201102_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watch_listed_by',
            field=models.ManyToManyField(related_name='watch_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ManyToManyField(related_name='listings_commented', to='auctions.Comment'),
        ),
    ]
